plugins {
    id 'com.android.application'
}

android {
    namespace 'ie.lzfood.cashier'
    compileSdk 34

    defaultConfig {
        applicationId 'ie.lzfood.cashier'
        minSdk 22
        targetSdk 22
        versionCode 13
        versionName '0.3.8'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
